openapi: 3.0.3
info:
  title: 'Social Crypto Documentation'
  description: 'Here you can find social crypto documentation api'
  version: 1.0.0
servers:
  -
    url: 'http://socialcrypto.test'
paths:
  '/api/auth/login/{provider}':
    get:
      summary: 'Redirect the user to the Provider authentication page.'
      operationId: redirectTheUserToTheProviderAuthenticationPage
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Please login using telegram or google'
                properties:
                  error:
                    type: string
                    example: 'Please login using telegram or google'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: provider
        description: ''
        example: dicta
        required: true
        schema:
          type: string
  '/api/auth/login/{provider}/callback':
    get:
      summary: 'Obtain the user information from Provider callback.'
      operationId: obtainTheUserInformationFromProviderCallback
      description: ''
      parameters: []
      responses:
        422:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  error: 'Please login using telegram or google'
                properties:
                  error:
                    type: string
                    example: 'Please login using telegram or google'
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: provider
        description: ''
        example: et
        required: true
        schema:
          type: string
  /api/auth/login:
    post:
      summary: 'Login user and create token'
      operationId: loginUserAndCreateToken
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: kacie08@example.org
                password:
                  type: string
                  description: ''
                  example: '+512Sr)clm7cHoT>U}b'
                remember_me:
                  type: boolean
                  description: ''
                  example: true
              required:
                - email
                - password
      security: []
  /api/auth/register:
    post:
      summary: 'Create user'
      operationId: createUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: aspernatur
                email:
                  type: string
                  description: ''
                  example: tara.sipes@example.net
                password:
                  type: string
                  description: ''
                  example: 'zc::m9'
                c_password:
                  type: string
                  description: 'The value and <code>password</code> must match.'
                  example: enim
              required:
                - name
                - email
                - password
                - c_password
      security: []
  /api/auth/logout:
    post:
      summary: 'Logout user (Revoke the token)'
      operationId: logoutUserRevokeTheToken
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/auth/user:
    get:
      summary: 'Get User Data'
      operationId: getUserData
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/social_categories:
    get:
      summary: 'Get the social categories'
      operationId: getTheSocialCategories
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/social_categories/create:
    post:
      summary: 'Create social category'
      operationId: createSocialCategory
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/tabs:
    get:
      summary: 'Get tabs of the user'
      operationId: getTabsOfTheUser
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/tabs/create:
    post:
      summary: 'Create tab user'
      operationId: createTabUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/wallets:
    get:
      summary: 'Get user wallets'
      operationId: getUserWallets
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/wallets/statistic:
    get:
      summary: ''
      operationId: getApiWalletsStatistic
      description: ''
      parameters: []
      responses:
        401:
          description: ''
          content:
            application/json:
              schema:
                type: object
                example:
                  message: Unauthenticated.
                properties:
                  message:
                    type: string
                    example: Unauthenticated.
      tags:
        - Endpoints
      security: []
  /api/wallets/create:
    post:
      summary: 'Create wallet user'
      operationId: createWalletUser
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
  /api/add-locale:
    post:
      summary: 'Add new locale'
      operationId: addNewLocale
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Translations
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                locale:
                  type: string
                  description: ''
                  example: en_PK
                name:
                  type: string
                  description: ''
                  example: asperiores
                active:
                  type: boolean
                  description: ''
                  example: true
              required:
                - locale
                - name
      security: []
  /api/add-translation:
    post:
      summary: 'Add translation'
      operationId: addTranslation
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Translations
      security: []
tags:
  -
    name: Endpoints
    description: ''
  -
    name: Translations
    description: ''
components:
  securitySchemes:
    default:
      type: http
      scheme: bearer
      description: 'You can retrieve your token by visiting your dashboard and clicking <b>Generate API token</b>.'
security:
  -
    default: []
